sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t radosnydzwon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

after_success:
  - docker build -t radosnydzwon/multi-client ./client
  - docker build -t radosnydzwon/multi-nginx ./nginx
  - docker build -t radosnydzwon/multi-server ./server
  - docker build -t radosnydzwon/multi-worker ./worker
