sudo: required
language: generic
services:
  - docker

script:
  - docker build -t radosnydzwon/multi-client ./client
  - docker build -t radosnydzwon/multi-nginx ./nginx
  - docker build -t radosnydzwon/multi-server ./server
  - docker build -t radosnydzwon/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push radosnydzwon/multi-client
  - docker push radosnydzwon/multi-nginx
  - docker push radosnydzwon/multi-server
  - docker push radosnydzwon/multi-worker
